# Generated by Django 4.2.11 on 2024-03-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.IntegerField(unique=True)),
                ('thread_id', models.IntegerField()),
                ('email_from', models.CharField(max_length=400)),
                ('email_to', models.CharField(max_length=400)),
                ('date', models.DateTimeField()),
                ('subject', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
